### ISSUE TITLE
Allow use of latest Jackson versions

### ISSUE THREAD

**Issue by lufecir** [eserating/siren4j#20]
Currently siren4j is using Jackson 2.1.4 (which dates from Feb. 2013).
It is not possible to upgrade to a later version of Jackson, since this causes Siren4j code to fail, which means our project is stuck with version 2.1.4 of Jackson.

Are there any plans for upgrading Siren4j to the latest version of Jackson (currently 2.6.1)?

**Comment by lufecir** [comment]
Hi, 

I would really like to move on with this. The old jackson version provided by siren4j is causing issues. We cannot upgrade jackson, but would need some of the new features (like jsr310 support).

Could you let me know if you consider moving to the latest jackson version an option? 

Thx.

Regards,

Luc

**Comment by eserating** [comment]
Will be fixed in 1.2.0, thanks for the pull request and sorry its taken me so long to get to it.
