### ISSUE TITLE
Unset values no longer suppressed with Jackson 2.7.0

### ISSUE THREAD

**Issue by chludwig-haufe** [eserating/siren4j#27]
Hi,

when we upgraded one of our projects to Spring Boot 1.4 (that depends on Jackson 2.8.1), we found that a [change in Jackson 2.7.0](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7#revert-back-expansion-of-non_empty-handling) relating to the handling of `Include.NON_DEFAULT` breaks the serialization of siren4j objects: 

If you annotate a _field_ with `@JsonInclude(Include.NON_DEFAULT)` (as, for instance, in `com.google.code.siren4j.component.impl.FieldImpl`), then it is omitted from the serialized JSON only if it is "empty" or its value is the default value of the the fields type.  It no longer matters how the default constructor of the class the field belongs to initializes the field.

For the Siren4J fields this means that `max`, `min`, and `maxLength` are all serialized with `-1` if you did not assign any values. Of course, `-1` indicates the attribute was not set, so we don't want to see this in the serialized output. I came across this issue in FieldImpl, I did not check whether other Siren4J components are affected by this Jackson change as well.

The attached unit tests demonstrates this issue: If you build it against Jackson 2.6.7, the test passes. If you build it agains Jackson 2.7.0, the test fails.

Do you see an easy workaround or fix?

Regards
Christoph

[siren4jJackson.zip](https://github.com/eserating/siren4j/files/417651/siren4jJackson.zip)

**Comment by eserating** [comment]
That is going to be a problem. Unfortunately I don't have an easy workaround.
I think the way around this for the Siren4J library is to use the Integer Object instead of the int primitive, that way unset would be null and would be excluded if the policy is set to Include.NOT_NULL. I need to think if changing these will cause backward compatibility issues.

Thank you for reporting the issue. I don't have an ETA for a fix yet.

**Comment by chludwig-haufe** [comment]
The relevant fields are all private and accessible to "normal" code via getters and setters only. So client code should not be affected by a switch to Integer references as long as the accessors take care of the (un)boxing.

Of course, code that accesses the fields via reflection might be affected. In case of Jackson that's intentional. Do you expect that many clients have code that (besides Jackson) works by reflection on the Siren4J objects?

**Comment by eserating** [comment]
Fixed in 2.0. by using Objects instead of primitives and allowing a null default value.
