### ISSUE TITLE
Can't output properties that are custom objects 

### ISSUE THREAD

**Issue by cedsan** [eserating/siren4j#33]
I've created my class with Siren4JEntity annotation and it extends BaseResource, but if my class have a field that's a reference type that's not a String it's not outputted to the produced representation obtained when used ReflectingConverter.newInstance().toEntity(), when according to the specification it should.
Am I missing some annotation to produce that result, or is it not supported.

**Comment by eserating-chwy** [comment]
Please attach your class and indicate the field with the issue.

**Comment by A40978** [comment]
`````
@Siren4JEntity(name = "observer", uri = "localhost:8080/observer/{number}")
class ObserverOM: BaseResource {

    val name:String
    val number: Int
    val email: String
    val avatar_url: String

    var observables: Collection<ObservableOM>? = null


    @JsonCreator
    constructor(@JsonProperty("name") name: String, @JsonProperty("number") number: Int,
                @JsonProperty("email") email: String, @JsonProperty("avatar_url") avatar_url: String) {
        this.name = name
        this.number = number
        this.email = email
        this.avatar_url = avatar_url
    }
}
```

**Comment by cedsan** [comment]
By chance I was able to obtain the desired representation. It was only necessary to use the @SirenProperty annotation and the field would be outputted to the representation. 
Although that annotation is addressed in the documentation, it is not documented for this specific purpose.

**Comment by eserating-chwy** [comment]
Yes, sorry I did not have a chance to look more closely at your issue. Using @SirenProperty will work because it gives the converter a hint that the field should be handled as a property. It auto detects simple property types such as int, Integer, String..etc so they don't need an annotation. But custom type will need the annotation to know your intention.
